name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, reopened, synchronize]

jobs:
  #soundness:
  #  name: Soundness
  #  uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
  #  with:
  #    license_header_check_project_name: "Swift.org"
  tests:
    name: tests
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:

      enable_linux_checks: true
      linux_swift_versions: "[\"6.2\"]"

      enable_macos_checks: false
      macos_xcode_versions: "[\"26\"]"

      enable_windows_checks: false
      windows_swift_versions: "[\"6.2\"]"
      


